A Coq formalisation of the R programming language

* Overview of the Project

This project is still in early development.

The project is divided in several passes, each providing a more typed
version of the R programming language.
Each pass is related to the previous by the corresponding Relation.v file.

For more details, see my reports (not in this repository).

* Building the Project

You need to install Coq and OCaml.
The simplest way is using Opam.

    sudo apt install opam
    opam install coq # TODO: Pin version?

Some tools are needed.

    # Install coq_makefile

You need to install Flocq.

    opam install coq-flocq

You need to compile TLC.

After all this, the Makefile should work.

    make


** low

This folder is a low-level specification of R.
It is the closest possible to the R source code (in C).

*** Rinternals.v

This file describes the data structures of R as they are in its C code.

*** RinternalsAux.v

Auxiliary definitions and properties about the data structures defined in
Rinternals.v.

*** State.v

This file provides a model for the C memory.

*** Globals.v

This file lists all global variables used in the C source code of R,
that are initialised, then never changed.

*** Monads.v

This file provides monads to manipulate R objects easily.

*** Reval.v

A Coq formalisation of the evaluation functions of R from its C code.
Note that only relevant definitions are translated here. Some are just
reinterpreted in Coq without following the original algorithm of the
C source. See report for more details.

*** Rinit.v

Initialises global variables.

*** Rfeatures.v

A Coq formalisation of additionnal functions of R from its C code.

*** Rinvariants.v

Proofs of some invariants respected by the functions defined in Reval.v,
Rinit.v, and Rfeatures.v.

*** Relation.v

Links the low-level formalisation to the C source code of R.

*** RelationCorrect.v

Proof that the relation defined in Module Relation holds along the
execution of the functions of Reval.

*** Extraction.v

Extract R interpreter into OCaml.

** structured

A formalisation of R a little more structured and typed than the low-level
representation.
In particular, the C memory has been abstracted out.

*** Rexpressions.v

In practise, the different language elements of R can not receive
anything. This version presents a version of the semantics in which
these assumptions are made explicit.

*** Relation.v

Links the structured-level formalisation to the low-level one.

** high

A High-level intuition of how R behaves.

*** Rstructures.v

High-level data structures.

*** Relation.v

Links the high-level formalisation to the structured-level one.

*** RReasoning.v

Provides tools to reason about R programs.

