argv <- list('([[:digit:]]+[.-]){1,}[[:digit:]]+', c('1.0', '1.0'), FALSE, FALSE, FALSE, FALSE, FALSE, FALSE); .Internal(grepl(argv[[1]], argv[[2]], argv[[3]], argv[[4]], argv[[5]], argv[[6]], argv[[7]], argv[[8]]))
argv <- list('\n', structure('c(person(\'José\', \'Pinheiro\', role = \'aut\',\n                    comment = \'S version\'),\n             person(\'Douglas\', \'Bates\', role = \'aut\',\n                    comment = \'up to 2007\'),\n             person(\'Saikat\', \'DebRoy\', role = \'ctb\',\n                    comment = \'up to 2002\'),\n             person(\'Deepayan\', \'Sarkar\', role = \'ctb\',\n                    comment = \'up to 2005\'),\n\t     person(\'R-core\', email = \'R-core@R-project.org\',\n                    role = c(\'aut\', \'cre\')),\n             person(\'EISPACK authors\', role = \'ctb\'))', .Names = 'Authors@R'), FALSE, FALSE, FALSE, TRUE, FALSE, FALSE); .Internal(grepl(argv[[1]], argv[[2]], argv[[3]], argv[[4]], argv[[5]], argv[[6]], argv[[7]], argv[[8]]))
argv <- list('([[:digit:]]+[.-]){1,}[[:digit:]]+', structure('7.3-26', .Names = 'Version'), FALSE, FALSE, FALSE, FALSE, FALSE, FALSE); .Internal(grepl(argv[[1]], argv[[2]], argv[[3]], argv[[4]], argv[[5]], argv[[6]], argv[[7]], argv[[8]]))
argv <- list('\n', c('### Encoding: UTF-8', '', '### Name: text', '### Title: Add Text to a Plot', '### Aliases: text text.default', '### Keywords: aplot', '', '### ** Examples', '', 'plot(-1:1, -1:1, type = \'n\', xlab = \'Re\', ylab = \'Im\')', 'K <- 16; text(exp(1i * 2 * pi * (1:K) / K), col = 2)', '', '## The following two examples use latin1 characters: these may not', '## appear correctly (or be omitted entirely).', 'plot(1:10, 1:10, main = \'text(...) examples\n~~~~~~~~~~~~~~\',', '     sub = \'R is GNU ©, but not ® ...\')', 'mtext(\'«Latin-1 accented chars»: éè øØ å<Å æ<Æ\', side = 3)', 'points(c(6,2), c(2,1), pch = 3, cex = 4, col = \'red\')', 'text(6, 2, \'the text is CENTERED around (x,y) = (6,2) by default\',', '     cex = .8)', 'text(2, 1, \'or Left/Bottom - JUSTIFIED at (2,1) by \'adj = c(0,0)\'\',', '     adj = c(0,0))', 'text(4, 9, expression(hat(beta) == (X^t * X)^{-1} * X^t * y))', 'text(4, 8.4, \'expression(hat(beta) == (X^t * X)^{-1} * X^t * y)\',', '     cex = .75)', 'text(4, 7, expression(bar(x) == sum(frac(x[i], n), i==1, n)))', '', '## Two more latin1 examples', 'text(5, 10.2,', '     \'Le français, c\'est façile: Règles, Liberté, Egalité, Fraternité...\')', 'text(5, 9.8,', '     \'Jetz no chli züritüütsch: (noch ein bißchen Zürcher deutsch)\')', '', '', ''), FALSE, FALSE, FALSE, TRUE, FALSE, FALSE); .Internal(grepl(argv[[1]], argv[[2]], argv[[3]], argv[[4]], argv[[5]], argv[[6]], argv[[7]], argv[[8]]))
argv <- list('x', 'x', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE); .Internal(grepl(argv[[1]], argv[[2]], argv[[3]], argv[[4]], argv[[5]], argv[[6]], argv[[7]], argv[[8]]))
argv <- list('^[[:space:]]*## No test:', 'Diagonal(3)', FALSE, FALSE, TRUE, FALSE, TRUE, FALSE); .Internal(grepl(argv[[1]], argv[[2]], argv[[3]], argv[[4]], argv[[5]], argv[[6]], argv[[7]], argv[[8]]))
argv <- list('n', 'nqr(x, ...)nqrR(qr, complete=FALSE, backPermute=TRUE)n', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE); .Internal(grepl(argv[[1]], argv[[2]], argv[[3]], argv[[4]], argv[[5]], argv[[6]], argv[[7]], argv[[8]]))
argv <- list('^prepare_Rd', structure(character(0), class = 'checkRd'), FALSE, FALSE, FALSE, FALSE, FALSE, FALSE); .Internal(grepl(argv[[1]], argv[[2]], argv[[3]], argv[[4]], argv[[5]], argv[[6]], argv[[7]], argv[[8]]))
argv <- structure(list(pattern = 'length', x = 'Lengths: 0, 1',     ignore.case = TRUE), .Names = c('pattern', 'x', 'ignore.case'));do.call('grepl', argv)
{ txt<-c("arm","foot","lefroo", "bafoobar"); grepl("foo", txt) }
{ .Internal(grepl(7, "7", F, F, F, F, F, F)) }
{ .Internal(grepl(character(), "7", F, F, F, F, F, F)) }
{ .Internal(grepl("7", 7, F, F, F, F, F, F)) }
{ .Internal(grepl('.+X', 'anXb', F, F, F, F, F, F)) }
{ .Internal(grepl('.+X', 'anXb', F, F, T, F, F, F)) }
