argv <- list(quote(cbind(X, M) ~ M.user + Temp + M.user:Temp + Soft)); .Internal(environment(argv[[1]]))
argv <- list(FALSE); .Internal(environment(argv[[1]]))
argv <- list(structure(numeric(0), .Dim = c(0L, 0L))); .Internal(environment(argv[[1]]))
argv <- list(structure(list(c0 = structure(integer(0), .Label = character(0), class = 'factor')), .Names = 'c0', row.names = character(0), class = structure('integer(0)', .Names = 'c0'))); .Internal(environment(argv[[1]]))
environment()
environment(`+`)
environment(print)
environment(FALSE)
environment(a~b)
environment(function(x) 1)
environment(NULL)
{ f <- y~z; class(f) <- c('myclass', class(f)); environment(f) }
