argv <- list(FALSE); .Internal(environmentName(argv[[1]]))
argv <- list(structure(list(c0 = structure(integer(0), .Label = character(0), class = 'factor')), .Names = 'c0', row.names = character(0), class = structure('integer(0)', .Names = 'c0'))); .Internal(environmentName(argv[[1]]))
argv <- list(structure(numeric(0), .Dim = c(0L, 0L))); .Internal(environmentName(argv[[1]]))
environmentName(globalenv())
environmentName(baseenv())
environmentName(emptyenv())
environmentName(parent.env(globalenv()))
environmentName(environment(sum))
environmentName(environment(lm))
