# @line

vector
vector ()
vector (NA)
# vector (0)
# vector (1)
vector (NULL)
vector ("NULL")
vector ("null")
vector ("DOUBLE")
vector ("double")
vector ("logical")
vector ("numeric")
vector ("real")
vector ("float")
vector ("int")
vector ("integer")
vector ("character")
vector ("boolean")
vector ("")
vector ("free")
vector ("new")
vector ("fun")
vector ("function")

vector ("double", 0)
vector ("numeric", 1)
vector ("character", 1.5)
vector ("integer", 10)
vector ("double", 10, 1)
vector ("numeric", -1)
vector ("character", NA)
vector ("integer", NaN)
# vector (0, "double")
# vector (1, "numeric")
# vector (NA, "character")
# vector ("logical", "logical")
vector ("integer", 0L)
vector ("double", 1L)
vector ("numeric", 10L)
vector ("character", -1L)
vector ("integer", 0i)
vector ("double", 1i)
vector ("logical", 10i)
vector ("double", -1i)

vector (length = 0L)
vector (length = 1L)
vector (length = 10L)

vector (mode = "logical")
vector (mode = "integer")
vector (length = 3L, mode = "numeric")
vector (mo = "numeric", le = 3L)
vector (x = 1)

vector ("NULL", 1L)
vector ("symbol", 1L)
vector ("pairlist", 1L)
vector ("closure", 1L)
vector ("environment", 1L)
vector ("promise", 1L)
vector ("language", 1L)
vector ("special", 1L)
vector ("builtin", 1L)
vector ("char", 1L)
vector ("logical", 1L)
vector ("integer", 1L)
vector ("double", 1L)
vector ("complex", 1L)
vector ("character", 1L)
vector ("...", 1L)
vector ("any", 1L)
vector ("list", 1L)
vector ("externalptr", 1L)
vector ("bytecode", 1L)
vector ("weakref", 1L)
#vector ("raw", 1L)
vector ("S4", 1L)
vector ("numeric", 1L)
vector ("name", 1L)
