# @line
# Tests about lazy evaluation and function application.
(function (x, y = x) { x <- 1 ; y ; x <- 2 ; y }) (3)
x <- 1 ; (function (x, y) { if (x) y }) (FALSE, x <- 2) ; x
x <- 1 ; (function (x, y, z) { z ; if (x) y }) (FALSE, x <- 2, x <- 3) ; x
x <- 1 ; (function (x, y, z) { z ; if (x) y }) (TRUE, x <- 2, x <- 3) ; x
x <- 1 ; (function (x, y) { (function (x, y) if (x) y) (x, y) }) (FALSE, x <- 2) ; x
x <- 0 ; (function (x, y = x <- 1) { x <- 2 ; y ; x }) (3) ; x
(function (x, y = x <- 1) { x }) (3)
z <- 1 ; (function (x, y = x) NULL) (z <- 2) ; z
z <- 1 ; (function (x, y = x) y) (z <- 2) ; z
apply <- function (f, ...) f (...) ; apply (function () 1) ; apply (function (x) x, 2) ; apply (function (x, y) x, 1) ; apply (function (x, y) y, 1, 2)
a <- b <- c <- d <- e <- 1 ; f <- function (x, y, ..., z) 1 ; f () ; f (a <- 2) ; a; f (a <- 3, b <- 4) ; a ; b ; f (a <- 5, b <- 6, d <- 7, e <- 8) ; a ; b ; c ; d ; e ; f (z = a <- 9, b <- 10, c <- 11, d <- 12, e <- 13) ; a ; b ; c ; d ; e
a <- b <- 1 ; f <- function (x, y) if (missing (y)) x ; f (a <- 2, b <- 3) ; a ; b ; f (a <- 4) ; a ; b ; f ()
missing ; missing (x)
missing ("x")
missing (1 + 2)
f <- function (x) missing (x) ; f () ; f (1) ; f (x = 1) ; f (1, 2)
f <- function (x) missing ("x") ; f () ; f (1) ; f (x = 1) ; f (1, 2)
f <- function (x) { y <- "x" ; missing (y) } ; f () ; f (1) ; f (x = 1) ; f (1, 2)
f <- function (x = 0) missing (x) ; f () ; f (1) ; f (x = 1) ; f (1, 2)
f <- function (x = NULL) missing (x) ; f () ; f (NULL) ; f (x = NULL) ; f (NULL, NULL)
f <- function (x = 0) { x ; missing (x) } ; f () ; f (1) ; f (x = 1) ; f (1, 2)
f <- function (x) { x ; missing (x) } ; f (1) ; f (x = 1) ; f (1, 2) ; f ()
f <- function (...) missing (...) ; f () ; f (1) ; f (1, 2) ; f (x = 1)
f <- function (x) missing (y) ; g <- function (y) f (y) ; g (x = 1)
f <- function (x) missing (y) ; g <- function (y) f (y) ; g (y = 1)
f <- function (x) missing (y) ; g <- function (y) f (y) ; g (1)
f <- function (x) missing ("y") ; g <- function (y) f (y) ; g (x = 1)
f <- function (x) missing ("y") ; g <- function (y) f (y) ; g (y = 1)
f <- function (x) missing ("y") ; g <- function (y) f (y) ; g (1)
f <- function (...) missing ("x") ; g <- function (x) f (x) ; g (x = 1)
f <- function (...) missing ("x") ; g <- function (x) f (x) ; g (1)
f <- function (x) function (y) missing (x) ; f () ; f ("y") ()
f <- function (m, x) m (x) ; f (missing) ; f (missing, NULL) ; f (missing, f ())
f <- function (x, y, z) x ; g <- function (x, ...) f (..., x) ; g (1) ; g (1, 2) ; g (1, 2, 3)
f <- function (x) x ; g <- function (...) f (...) ; g (1) ; g ()
f <- function (x, y, z) y ; g <- function (...) f (...) ; g (1, 2, 3) ; g (1, 2) ; g (y = 2)
f <- function (...) ... ; f (1)
head <- function (x, ...) x ; head (1, 2, 3) ; head ()
f <- function (x, ...) if (x) TRUE else f (TRUE, x, ...) ; f (FALSE) ; f (FALSE, FALSE)
f <- function (x, ...) if (x) TRUE else f (..., x) ; f (FALSE, FALSE, TRUE)
# f <- function (...) ..2 ; f (1, 2, 3) ; f (1, 2) ; f (1)
# f <- function (...) ..10 ; f (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11) ; f (10)
# f <- function (...) missing (..2) ; f (1) ; f (1, 2) ; f (1, 2, 3)
# f <- function (...) missing (..100) ; f (1)
# f <- function (...) missing (..999999999) ; f (1)
# f <- function (...) missing (..999999999999999999) ; f () ; f (1) ; f (1, 2)
# f <- function (...) ..0 ; f (1) ; f ()
# f <- function (...) ..1 ; f (1) ; f ()
# f <- function (...) ..01 ; f (1) ; f ()
# f <- function (...) ..00 ; f (1) ; f ()
function (..., x, y, z, ...) x
function (x, y, z, x) y
f <- function (x, y) x ; f (x = 1, "x" = 1)
f <- function (x = x) x ; f (1) ; f ()
f <- function (x = 0, ...) x ; f () ; f (1, 2, 3) ; f (1, 2, x = 3)
g <- function (x) x ; f <- function (y = 0, ...) g (...) ; f (1, 2) ; f (1)
g <- function () 1 ; f <- function (...) g (...) ; f ()
g <- function (x) x ; f <- function (...) g (...) ; f (2) ; f ()
g <- function (x) x ; f <- function (...) g (...) ; f (1, 2)
g <- function (x) x ; f <- function (...) g (...) ; g <- function (x, y) x ; f (1) ; f (1, 2) ; f (1, 2, 3)
g <- function (x, y) x * y ; f <- function (...) g (...) ; f (2, 3) ; f (2, 3, 5)
g <- function (x, y) x * y ; f <- function (...) g (...) ; f (list (2, 3))
g <- function (x, y, z) x * y * z ; f <- function (...) g (...) ; f (2, 3, 5) ; f (2, 3, 5, 7)
g <- function (x, y, z) x * y * z ; f <- function (...) g (...) ; f (list (2, 3, 5))
g <- function (x, y, z) x * y * z ; f <- function (...) g (...) ; f (x = 2, y = 3, z = 5) ; f (a = 2, b = 3, c = 5)
f <- function (ab, abc) ab ; f (a = 1, ab = 2)
f <- function (ab, abc) abc ; f (a = 1, ab = 2)
f <- function (..., x) 1 ; f (1, 2, 3, 4, 5) ; f (1) ; f ()
f <- function (..., x) x ; f (1, 2, 3, 4, 5) ; f (1) ; f ()
f <- function (..., x) x ; f (x = 2, 3, 5, 7, 5) ; f (1, 2, x = 3, 4, 5) ; f (1, 2, 3, 4, x = 5) ; f ("x" = 1, 2, 3, 4, 5) ; f (1, 2, "x" = 3, 4, 5) ; f (1, 2, 3, 4, "x" = 5) ; f (x = 1, 2, 3, 4, "x" = 5)
g <- function (x, y, z) x * y * z ; f <- function (..., x) g (...) ; f (2, 3, 5, 7) ; f (x = 2, 3, 5, 7) ; f (2, 3, x = 5, 7) ; f (2, 3, 5, x = 7) ; f ("x" = 2, 3, 5, 7) ; f (2, 3, "x" = 5, 7) ; f (2, 3, 5, "x" = 7) ; f (x = 2, 3, 5, "x" = 7)
f <- function (x, ...) 1 ; f (1, 2, 3, 4, 5) ; f (1) ; f ()
f <- function (x, ...) x ; f (1, 2, 3, 4, 5) ; f (1) ; f ()
f <- function (x, ...) x ; f (x = 2, 3, 5, 7, 5) ; f (1, 2, x = 3, 4, 5) ; f (1, 2, 3, 4, x = 5) ; f ("x" = 1, 2, 3, 4, 5) ; f (1, 2, "x" = 3, 4, 5) ; f (1, 2, 3, 4, "x" = 5) ; f (x = 1, 2, 3, 4, "x" = 5)
g <- function (x, y, z) x * y * z ; f <- function (x, ...) g (...) ; f (2, 3, 5, 7) ; f (x = 2, 3, 5, 7) ; f (2, 3, x = 5, 7) ; f (2, 3, 5, x = 7) ; f ("x" = 2, 3, 5, 7) ; f (2, 3, "x" = 5, 7) ; f (2, 3, 5, "x" = 7) ; f (x = 2, 3, 5, "x" = 7)
g <- function (a, b) a ; f <- function (x, ...) g (...) ; f (1, 2, 3) ; f (1, 2) ; f (1, 2, x = 3) ; f (a = 1, 2, 3) ; f (b = 1, 2, x = 3)
f <- function (..., ab) ab ; f (1, 2, ab = 3, 4, 5) ; f (1, 2, a = 3, 4, 5)
g <- function () 1 ; f <- function (g) g () ; f (2) ; f (function () 3)
g <- function () 1 ; f <- function (g) { g <- 4 ; g () } ; f (2) ; f (function () 3) ; g <- 5 ; g ()
g <- function () 1 ; f <- function (g) (g) () ; f (function () 3) ; f (2)
f <- function (x) 1 ; f (2) ; f () ; f (a) ; f (..1) ; f (TRUE (3)) ; f (1, 2)
1 ()
TRUE ()
FALSE ()
NULL ()
NA ()
NaN ()
"1" ()
"" ()

f <- { function () 1 + 1 } ; f ; f ()
f <- { function () break + 1 } ; f ; f ()
