argv <- list('kendall', c('pearson', 'kendall', 'spearman'), 0L, TRUE); .Internal(pmatch(argv[[1]], argv[[2]], argv[[3]], argv[[4]]))
argv <- list('month', c('secs', 'mins', 'hours', 'days', 'weeks', 'months', 'years', 'DSTdays'), NA_integer_, FALSE); .Internal(pmatch(argv[[1]], argv[[2]], argv[[3]], argv[[4]]))
argv <- list(c(NA_character_, NA_character_, NA_character_, NA_character_), 'NA', NA_integer_, TRUE); .Internal(pmatch(argv[[1]], argv[[2]], argv[[3]], argv[[4]]))
argv <- list('maximum', 'euclidian', NA_integer_, FALSE); .Internal(pmatch(argv[[1]], argv[[2]], argv[[3]], argv[[4]]))
argv <- list('fanny.object.', 'fanny.object', 0L, FALSE); .Internal(pmatch(argv[[1]], argv[[2]], argv[[3]], argv[[4]]))
argv <- list(c('alpha', 'col', 'border', 'lty', 'lwd'), c('col', 'border', 'alpha', 'size', 'height', 'angle', 'density'), NA_integer_, TRUE); .Internal(pmatch(argv[[1]], argv[[2]], argv[[3]], argv[[4]]))
argv <- list('unique.', 'unique.array', 0L, FALSE); .Internal(pmatch(argv[[1]], argv[[2]], argv[[3]], argv[[4]]))
argv <- list(character(0), c('labels', 'col', 'alpha', 'adj', 'cex', 'lineheight', 'font'), NA_integer_, TRUE); .Internal(pmatch(argv[[1]], argv[[2]], argv[[3]], argv[[4]]))
pmatch(NULL, 1)
pmatch(1, NULL)
pmatch(x=NULL, table=NULL)
pmatch(x=1)
pmatch(table=1)
pmatch(1:5, c(1,3), nomatch=NULL)
pmatch(1:5, c(1,3), nomatch='str')
pmatch(1:5, c(1,3), duplicates.ok=42)
