argv <- list(.Primitive('+'), TRUE); .Internal(print.function(argv[[1]], argv[[2]]))
argv <- list(.Primitive('if'), TRUE); .Internal(print.function(argv[[1]], argv[[2]]))
argv <- list(.Primitive('c'), TRUE); .Internal(print.function(argv[[1]], argv[[2]]))
argv <- list(.Primitive('.Internal'), TRUE); .Internal(print.function(argv[[1]], argv[[2]]))
argv <- list(.Primitive('log'), TRUE); .Internal(print.function(argv[[1]], argv[[2]]))
