f <- function() { on.exit(print('test')); print('some') }; f()
f <- function() { on.exit(print('test', TRUE)); print('some') }; f()
f <- function() { on.exit(print('test')); on.exit(); print('some') }; f()
f <- function() { on.exit(print('test')); on.exit(print('test2', TRUE)); print('some') }; f()
f <- function() { on.exit(print('test')); on.exit(print('test2')); print('some') }; f()
f <- function() { on.exit(print('test', TRUE)); on.exit(print('test2')); print('some') }; f()
f <- function() { on.exit(print('test')); on.exit(print('test2')); print('some'); on.exit() }; f()
f <- function() { on.exit() }; f()
f <- function() { on.exit(return(5)); return(1) }; f()
