argv <- list(c('\'time\'', '\'status\''), 128); .Internal(strtrim(argv[[1]], argv[[2]]))
argv <- list('2014-03-17 14:47:20', 8); .Internal(strtrim(argv[[1]], argv[[2]]))
argv <- list(c('\'1\'', '\'2\'', NA), 128); .Internal(strtrim(argv[[1]], argv[[2]]))
argv <- list(c('\'gray17\'', '\'grey17\''), 128); .Internal(strtrim(argv[[1]], argv[[2]]))
argv <- list(structure('\'@CRAN@\'', .Names = 'CRAN'), 128); .Internal(strtrim(argv[[1]], argv[[2]]))
argv <- list('FALSE', FALSE); .Internal(strtrim(argv[[1]], argv[[2]]))
argv <- list(character(0), 40L); .Internal(strtrim(argv[[1]], argv[[2]]))
v <- c('a', 'fooooo', 'bbbbbb', 'cccccccccc', 'dd', NA); names(v) <- as.character(1:6); strtrim(v, c(2L, 5L))
v <- c('a', 'fooooo', 'bbbbbb', 'cccccccccc', 'dd', NA); names(v) <- as.character(1:6); strtrim(v, c(2, 5))
.Internal(strtrim('abc', NULL))
.Internal(strtrim('abc', ))
