rep_len(1, 2)
rep_len(3.14159, 3)
rep_len('RepeatTest', 5)
rep_len(2+6i, 4)
rep_len(TRUE, 2)
x<-as.raw(16); rep_len(x, 2)
rep_len(1:4, 10)
rep_len(1:4, 3)
rep_len(1:4, 4)
rep_len(c(3.1415, 0.8), 1)
rep_len(c(2i+3, 4+2i), 4)
x<-as.raw(16); y<-as.raw(5); rep_len(c(x, y), 5)
rep_len(x=1:2, length.out=4)
rep_len(length.out=4, x=1:2)
rep_len(length.out=4, 'text')
rep_len(4, x='text')
x<-'text'; length.out<-4; rep_len(x=x, length.out=length.out)
x<-'text'; length.out<-4; rep_len(length.out=length.out, x=x)
rep_len(c('abcd', 'efg'), 7)
rep_len(c('abcd', 'efg'), 14)
rep_len(c('abcd', 'efg'), 8)
rep_len(c('abcd', 'efg'), 0)
rep_len(c('abcd', 'efg'), 1)
rep_len(c('abcd', 'efg'), 2)
rep_len(function() 42, 7)
rep_len(7, '7')
rep_len(7, integer())
rep_len(7, NA)
rep_len(7, NULL)
rep_len(7, c(7, 42))
rep_len(1L, 4L)
rep_len(c(a=1,b=4), 4)
rep_len(expression(1,4,'foo'), 7)
