rawToBits(raw(0))
rawToBits(raw(10))
rawToBits(as.raw(0))
rawToBits(as.raw(1))
rawToBits(as.raw(255))
rawToBits(c(as.raw(1), as.raw(255)))
rawToBits(raw(0), raw(1))
rawToBits(as.raw(0:255))
rawToBits(as.raw(c(0,1,255)))
rawToBits(as.raw(1)[1])
rawToBits(0:255)
rawToBits(NA)
rawToBits(NULL)
rawToBits(list(list()))
rawToBits(list(NULL))
rawToBits(c(NULL))
rawToBits(integer(0))
rawToBits(double(0))
rawToBits(01)
rawToBits('a')
rawToBits(new.env())
rawToBits(environment)
rawToBits(stdout())
