argv <- list('^(([^:]+)://)?([^:/]+)(:([0-9]+))?(/.*)', 'http://stat.umn.edu:80/xyz', FALSE, FALSE, FALSE); .Internal(regexec(argv[[1]], argv[[2]], argv[[3]], argv[[4]], argv[[5]]))
regexpr("^(?:(?:^[([^]]+)])?(?:'?([^']+)'?!)?([a-zA-Z0-9:-$[]]+)|(.*))$", 'A1', perl=T)
regexpr("^(?:(?:^[([^]]+)])?(?:'?([^']+)'?!)?([a-zA-Z0-9:-$[]]+)|(.*))$", 'A1A1', perl=T)
regexpr("^(?:(?:^[([^]]+)])?(?:'?([^']+)'?!)?([a-zA-Z0-9:-$[]]+)|(.*))$", 'A1 A1', perl=T)
regexpr("^(?<n1>:(?:^[([^]]+)])?(?:'?([^']+)'?!)?([a-zA-Z0-9:-$[]]+)|(.*))$", 'A1', perl=T)
regexpr("^(?<n1>:(?:^[([^]]+)])?(?<n2>:'?([^']+)'?!)?([a-zA-Z0-9:-$[]]+)|(.*))$", 'A1', perl=T)
regexpr("^(?:(?:^[([^]]+)])?(?<n2>:'?([^']+)'?!)?([a-zA-Z0-9:-$[]]+)|(.*))$", 'A1', perl=T)
regexpr("^((.*))$", 'A1', perl=T)
regexpr("^(?<n>(.*))$", 'A1', perl=T)
regexpr("^(.*)$", 'A1', perl=T)
regexpr("^(?<n>.*)$", 'A1', perl=T)
regexpr("^(([A-Z)|([a-z]))$", 'Aa', perl=T)
regexpr("^(([A-Z)|([a-z]))$", c('A', 'Aa'), perl=T)
regexpr("^(([A-Z)|([a-z]))$", c('Aa', 'A'), perl=T)
