argv <- list('.', '.', c('0.02', '0.06', '0.11', '0.22', '0.56', '1.1')); .Internal(chartr(argv[[1]], argv[[2]], argv[[3]]))
argv <- list('iXs', 'why', 'MiXeD cAsE 123'); .Internal(chartr(argv[[1]], argv[[2]], argv[[3]]))
argv <- list('a-cX', 'D-Fw', 'MiXeD cAsE 123'); .Internal(chartr(argv[[1]], argv[[2]], argv[[3]]))
argv <- list('.', '.', character(0)); .Internal(chartr(argv[[1]], argv[[2]], argv[[3]]))
argv <- structure(list(old = 'NA', new = 'na', x = c('NA', NA,     'BANANA')), .Names = c('old', 'new', 'x'));do.call('chartr', argv)
chartr(c('abq'), 'cd', c('agbc', 'efb'))
chartr(c('a','b'), c('c', 'e'), c('abc', 'efb'))
chartr(c('a','b'), c(3, 2), c('abc', 'efb'))
chartr(c(3, 2), c('q', 'c'), c('abc', 'efb'))
chartr('0-5', '0-3', 'ah3g4t')
chartr('0-5', '0-', 'ah3g4t')
chartr('0-5', '045', 'ah3g4t')
