(df <- deriv(~x^2*sin(x), "x", function.arg=TRUE));df(0)
(df <- deriv(~x^2*sin(x), "x", function.arg=c("x")));df(0)
(df <- deriv(~x^2*sin(x), "x", function.arg=function(x=1){}));df(0)
(df <- deriv(~x^2*sin(x), "x", function.arg=function(x)NULL));df(0)
environment(deriv((y ~ sin(cos(x) * y)), c('x','y'), func = TRUE))
environment(local(deriv((y ~ sin(cos(x) * y)), c('x','y'), func = TRUE)))
environment(local(deriv((y ~ sin(cos(x) * y)), c('x','y'), func = deriv)))
(df <- deriv(expression(x^2*sin(x)), "x"));df(0)
(df <- deriv(quote(x^2*sin(x)), "x"));df(0)
g<-quote(x^2);(df <- deriv(g, "x"));df(0)
(df <- deriv(1, "x"));df(0)
x<-1;(df <- deriv(x, "x"));df(0)
