crc64()
crc64('a')
.Internal(crc64())
.Internal(crc64('a'))
.Internal(crc64(paste(c(letters, LETTERS, 0:9), collapse="")))
.Internal(crc64(c('a')))
.Internal(crc64('a', 'b'))
.Internal(crc64(c(1, 2)))
.Internal(crc64(c('a', 'b')))
.Internal(crc64(NA))
.Internal(crc64(NULL))
.Internal(crc64(list(list())))
.Internal(crc64(list(NULL)))
.Internal(crc64(c(NULL)))
.Internal(crc64(integer(0)))
.Internal(crc64(double(0)))
.Internal(crc64(01))
.Internal(crc64(new.env()))
.Internal(crc64(environment))
.Internal(crc64(stdout()))
.Call(utils:::C_crc64, 'abc')
.Call(utils:::C_crc64, paste(c(letters, LETTERS, 0:9), collapse=""))
.Call(utils:::C_crc64, c('a'))
.Call(utils:::C_crc64, 'a', 'b')
.Call(utils:::C_crc64)
.Call(utils:::C_crc64, c(1, 2))
.Call(utils:::C_crc64, c('a', 'b'))
.Call(utils:::C_crc64, NA)
.Call(utils:::C_crc64, NULL)
.Call(utils:::C_crc64, list(list()))
.Call(utils:::C_crc64, list(NULL))
.Call(utils:::C_crc64, c(NULL))
.Call(utils:::C_crc64, integer(0))
.Call(utils:::C_crc64, double(0))
.Call(utils:::C_crc64, 01)
.Call(utils:::C_crc64, new.env())
.Call(utils:::C_crc64, environment)
.Call(utils:::C_crc64, stdout())
