lengths(c(1,2,3))
lengths(1:11)
lengths(list(1, c(1,2), 1:3))
lengths(list(1, list(1, c(1,2)), 1:3))
lengths(NULL)
lengths(list(a=1, b=c(1,2)))
lengths(list(a=1, b=c(1,2)), use.names=FALSE)
x<-c(1,2); names(x) <- c('a', 'b'); lengths(x)
x<-c(1,2); names(x) <- c('a', 'b'); lengths(x, use.names=FALSE)
lengths(matrix(1:4, nrow=2, ncol=2, dimnames=list(c('a', 'b'), c('d', 'e'))))
lengths(quote(a))
lengths(42, use.names='as')
