min <- 1; match.fun('min')
min <- 1; match.fun('min', descend=T)
min <- 1; match.fun('min', descend=F)
min <- 1; match.fun(min)
min <- 1; match.fun(min, descend=T)
min <- 1; match.fun(min, descend=F)
f <- function() { min <- 1; match.fun('min')}; f()
f <- function() { min <- 1; match.fun('min', descend=T)}; f()
f <- function() { min <- 1; match.fun('min', descend=F)}; f()
f <- function() { min <- 1; match.fun(as.symbol('min'))}; f()
f <- function() { min <- 1; match.fun(as.symbol('min'), descend=T)}; f()
f <- function() { min <- 1; match.fun(as.symbol('min'), descend=F)}; f()
x <- min; f <- function() { min <- 1; match.fun(x)}; f()
x <- min; f <- function() { min <- 1; match.fun(x, descend=T)}; f()
x <- min; f <- function() { min <- 1; match.fun(x, descend=F)}; f()
f <- function(x) { min <- 1; match.fun(x)}; f(min)
f <- function(x) { min <- 1; match.fun(x, descend=T)}; f(min)
f <- function(x) { min <- 1; match.fun(x, descend=F)}; f(min)
min <- 1; f <- function() { match.fun('min')}; f()
min <- 1; f <- function() { match.fun('min', descend=T)}; f()
min <- 1; f <- function() { match.fun('min', descend=F)}; f()
min <- 1; f <- function() { match.fun(as.symbol('min'))}; f()
min <- 1; f <- function() { match.fun(as.symbol('min'), descend=T)}; f()
min <- 1; f <- function() { match.fun(as.symbol('min'), descend=F)}; f()
x <- min; min <- 1; f <- function() { match.fun(x)}; f()
x <- min; min <- 1; f <- function() { match.fun(x, descend=T)}; f()
x <- min; min <- 1; f <- function() { match.fun(x, descend=F)}; f()
min <- 1; f <- function(x) { match.fun(x)}; f(min)
min <- 1; f <- function(x) { match.fun(x, descend=T)}; f(min)
min <- 1; f <- function(x) { match.fun(x, descend=F)}; f(min)
min <- 1; f <- function(min) { match.fun(min)}; f(min)
min <- 1; f <- function(min) { match.fun(min, descend=T)}; f(min)
min <- 1; f <- function(min) { match.fun(min, descend=F)}; f(min)
min <- 1; f <- function(min) { match.fun(min)}; f(baz)
min <- 1; f <- function(min) { match.fun(min, descend=T)}; f(baz)
min <- 1; f <- function(min) { match.fun(min, descend=F)}; f(baz)
min <- 1; f <- function(x) { match.fun(x)}; f(c('min'))
min <- 1; f <- function(x) { match.fun(x)}; f(c('min', 'max'))
min <- 1; f <- function() { match.fun(c('min'))}; f()
min <- 1; f <- function() { match.fun(c('min', 'max'))}; f()
min <- 1; f <- function() { match.fun(c(1L))}; f()
min <- 1; f <- function() { match.fun(as.raw(100))}; f()
x <- min; f <- function(x) { min <- 1; match.fun(x, descend=T)}; f2 <- function(y) f(y); f2(min)
x <- min; f <- function(x) { min <- 1; match.fun(x, descend=T)}; f2 <- function(max) f(max); f2(min)
x <- min; f <- function(x) { min <- function(x) x; match.fun(x, descend=T)}; f(min)
min <- function(x) x; f <- function(x) { match.fun(x, descend=T)}; f(min)
f <- function(x) { match.fun(x, descend=T)}; f2 <- function() { min <- max; f(min) }; f2()
{ foo <- function() { myfunc <- function(x) 42; lapply(2, 'myfunc'); }; boo <- function() { myfunc <- function(x) 42; lapply(2, 'myfunc'); }; list(foo = foo(), boo = boo()); }


