match.arg(NULL, c('a'))
match.arg(NULL, c(1))
match.arg(NULL, c())
match.arg(NULL, character())
match.arg(NULL, list())
match.arg(NULL, NULL)
match.arg(c('a'), c('a'), T)
match.arg(c('a', 'b'), c('a'), F)
match.arg(c('a', 'b'), c('a'), T)
match.arg(c('a', 'b'), c('b'), T)
match.arg(c('a', 'b', 'c'), c('b'), T)
match.arg(c('a', 'b', 'c'), c('b', 'c'), T)
match.arg(c('a', 'b', 'c'), c('c', 'b'), T)
match.arg(c('a', 'b', 'c'), c('a', 'b'), T)
match.arg(c('a', 'b', 'c'), c('a', 'c'), T)
match.arg(c('1'), c(1), T)
match.arg(c('1', '1'), c(1), T)
{ v<-c('a', 'b'); names(v) <- c('an', 'ab'); match.arg(c('a', 'b'), v, T)}
match.arg(c('a'), list('a', 'b'), T)
match.arg(c('a'), list(a='a', b='b'), T)
match.arg(c('1'), list(1), T)
match.arg(list('a', 'b'), 'c', T)
match.arg(c('a'), c('b'), T)
