argv <- list(c(1.81566026854212e-304, 0, 0, 0, 0, 0, 0, 0, 0,     0, 0, 0, 0, 0, 0, 0, 0, 0, 0));do.call('anyNA', argv)
anyNA(list(list(c(NA)),c(1)), recursive=TRUE)
anyNA(list(list(c(NA)),c(1)), recursive=FALSE)
anyNA(list(list(c(NA)),c(1)), recursive=c(FALSE,TRUE))
anyNA(list(list(4,5,NA), 3), recursive=TRUE)
anyNA(c(1, 2, 3))
anyNA(c(1, NA, 3))
anyNA(c(1, NA, 3), recursive = TRUE)
anyNA(list(a = c(1, 2, 3), b = 'a'))
anyNA(list(a = c(1, NA, 3), b = 'a'))
anyNA(list(a = c('asdf', NA), b = 'a'))
anyNA(list(a = c(NA, 3), b = 'a'))
anyNA(list(a = NA, b = 'a'))
anyNA(list(a = NA))
anyNA(list(1, NA))
anyNA(list(a = c('asdf', NA), b = 'a'), recursive = TRUE)
anyNA(list(a = c(NA, 3), b = 'a'), recursive = TRUE)
anyNA(list(a = NA, b = 'a'), recursive = TRUE)
anyNA(list(a = NA), recursive = TRUE)
anyNA(list(1, NA), recursive = TRUE)
anyNA(list(a = c(1, 2, 3), b = 'a'), recursive = TRUE)
anyNA(list(a = c(1, NA, 3), b = 'a'), recursive = TRUE)
anyNA(list(a = c(1, 2, 3), b = list(NA, 'a')), recursive = TRUE)
